#!/usr/bin/env python3
"""
visualise_items.py
==================
Produce bar-chart visualizations from items-analysis.json
(generated by analyse_items.py).

Charts produced (saved to output/):
  fig1_metadata_format.png   — record count by metadata format
  fig2_sparte.png            — record count by DDB Sparte (German labels)
  fig3_providers_top20.png   — top-20 providers by record count
  fig4_dc_type_top20.png     — top-20 dcType values (German labels)
  fig5_dc_subject_top30.png  — top-30 dcSubject values (German labels)
  fig6_view_fields_top20.png — top-20 view field names by occurrence count

Note: labels remain in German. Run translate_and_plot.py or plot_latex_figs.py
for English-translated versions.

Usage
-----
    python scripts/visualise_items.py
"""

import json
import os
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
from pathlib import Path

PROJECT  = Path(__file__).resolve().parent.parent
IN_PATH  = PROJECT / "output" / "items-analysis.json"
OUT_DIR  = PROJECT / "output"

COLORS = {
    "blue":   "#4C72B0",
    "green":  "#55A868",
    "orange": "#DD8452",
    "red":    "#C44E52",
    "purple": "#8172B3",
    "teal":   "#64B5CD",
}

plt.rcParams.update({
    "font.family": "sans-serif",
    "axes.spines.top": False,
    "axes.spines.right": False,
    "axes.grid": True,
    "axes.grid.axis": "x",
    "grid.alpha": 0.4,
    "figure.dpi": 150,
})


def save(fig, name):
    path = os.path.join(OUT_DIR, name)
    fig.savefig(path, bbox_inches="tight")
    plt.close(fig)
    print(f"  Saved: {name}")


def hbar(labels, values, title, xlabel, color, figsize=(9, None), fontsize=10):
    """Horizontal bar chart, labels on y-axis."""
    n = len(labels)
    h = figsize[1] or max(4, n * 0.4)
    fig, ax = plt.subplots(figsize=(figsize[0], h))
    bars = ax.barh(range(n), values, color=color, height=0.6)
    ax.set_yticks(range(n))
    ax.set_yticklabels(labels, fontsize=fontsize)
    ax.invert_yaxis()
    ax.set_xlabel(xlabel, fontsize=10)
    ax.set_title(title, fontsize=12, fontweight="bold", pad=10)
    # Value annotations
    for bar, val in zip(bars, values):
        ax.text(
            bar.get_width() + max(values) * 0.01,
            bar.get_y() + bar.get_height() / 2,
            f"{val:,}",
            va="center", ha="left", fontsize=fontsize - 1,
        )
    ax.set_xlim(0, max(values) * 1.15)
    ax.xaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f"{int(x):,}"))
    fig.tight_layout()
    return fig


# ── load data ─────────────────────────────────────────────────────────────────

with open(IN_PATH, encoding="utf-8") as f:
    data = json.load(f)

total = data["total_records"]
print(f"Total records: {total:,}\n")

# ── fig 1: metadata format ────────────────────────────────────────────────────

mf = data["metadata_format"]
labels = [x["label"] for x in mf]
counts = [x["count"] for x in mf]

fig = hbar(labels, counts,
           title=f"Records by Metadata Format (N={total:,})",
           xlabel="Number of records",
           color=COLORS["blue"])
save(fig, "fig1_metadata_format.png")

# ── fig 2: sparte ─────────────────────────────────────────────────────────────

sp = [x for x in data["sparte"] if x["uri"].startswith("http://ddb.vocnet.org/")]
labels = [x["label"] for x in sp]
counts = [x["count"] for x in sp]

fig = hbar(labels, counts,
           title=f"Records by DDB Sparte (N={total:,})",
           xlabel="Number of records",
           color=COLORS["green"])
save(fig, "fig2_sparte.png")

# ── fig 3: top-20 providers ───────────────────────────────────────────────────

TOP = 20
prov = data["provider"][:TOP]
labels = [x["name"] if x["name"] else x["provider_id"] for x in prov]
counts = [x["count"] for x in prov]

fig = hbar(labels, counts,
           title=f"Top {TOP} Providers by Record Count",
           xlabel="Number of records",
           color=COLORS["orange"],
           figsize=(11, None), fontsize=9)
save(fig, "fig3_providers_top20.png")

# ── fig 4: top-20 dcType values ───────────────────────────────────────────────

dct = data["dc_type"][:TOP]
labels = [x["value"] for x in dct]
counts = [x["count"] for x in dct]

fig = hbar(labels, counts,
           title=f"Top {TOP} dc:Type Values",
           xlabel="Number of records",
           color=COLORS["red"])
save(fig, "fig4_dc_type_top20.png")

# ── fig 5: top-30 dcSubject values ────────────────────────────────────────────

TOP_S = 30
dcs = data["dc_subject"][:TOP_S]
labels = [x["value"] for x in dcs]
counts = [x["count"] for x in dcs]

fig = hbar(labels, counts,
           title=f"Top {TOP_S} dc:Subject Values",
           xlabel="Number of records",
           color=COLORS["purple"],
           figsize=(11, None), fontsize=9)
save(fig, "fig5_dc_subject_top30.png")

# ── fig 6: top-20 view field names ────────────────────────────────────────────

vf_sorted = sorted(
    data["view_fields"].items(),
    key=lambda kv: -kv[1]["total_occurrences"],
)[:TOP]
labels = [name for name, _ in vf_sorted]
counts = [info["total_occurrences"] for _, info in vf_sorted]

fig = hbar(labels, counts,
           title=f"Top {TOP} Display Field Names (by occurrence)",
           xlabel="Total occurrences across all records",
           color=COLORS["teal"],
           figsize=(11, None), fontsize=9)
save(fig, "fig6_view_fields_top20.png")

print("\nDone.")
